---
abstract: 'AbstractFactory behaviour as a Moose extension'
author:
  - 'Mike Whitaker  C<< <mike@altrion.org> >>'
build_requires:
  Test::Exception: 0
  Test::Moose: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AbstractFactory
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  Moose::Autobox: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.3.1
